# Generated by Django 2.2.1 on 2019-05-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_sub_name', models.CharField(blank=True, max_length=100)),
                ('org_crn', models.CharField(blank=True, max_length=10, unique=True)),
                ('org_header', models.CharField(blank=True, max_length=20)),
                ('org_address', models.CharField(blank=True, max_length=200)),
                ('org_tel_num', models.CharField(blank=True, max_length=50)),
                ('org_desc', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
    ]
