# Generated by Django 2.2.4 on 2019-08-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_crn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_header',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_sub_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_tel_num',
            field=models.CharField(max_length=50),
        ),
    ]
