# Generated by Django 2.2.1 on 2019-06-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='users',
        ),
    ]
