# Generated by Django 2.2.1 on 2019-06-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190604_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='corp_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='corp_num',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
