# Generated by Django 2.2.4 on 2019-08-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20190808_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedb',
            name='inflow_path',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
