# Generated by Django 2.2.4 on 2019-08-14 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_landingpagedb_inflow_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagedb',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
