# Generated by Django 2.2.4 on 2019-08-14 07:42

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_landingpagedb_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagedb',
            name='user_agent',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
