# Generated by Django 2.2.1 on 2019-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
