# Generated by Django 2.2.1 on 2019-05-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190523_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone_num',
            field=models.CharField(max_length=11),
        ),
    ]
