# Generated by Django 2.2.4 on 2019-08-13 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190611_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.Organization'),
        ),
    ]
